### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by EmiMidnight** [bagelswitch/ArcadeServLinux#1]
What the fuck is your problem?

**Comment by bagelswitch** [comment]
Uh, hi . . . is there something you don't like about this repo? I can address whatever it is, if you can be a little more specific . . .

**Comment by bagelswitch** [comment]
> What the fuck is your problem?

Given no other information, I guess the best thing to do here is make this repo private . . . ? Doing so I assume will prevent any further issue comments, so hopefully you get a notification with this one - if so, I'd really appreciate a message in discord, if you have a moment, explaining what you object to - I respect you and your work, so would like to know what I did here to offend . . .
